name: real-valued-acs-system
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - jupyter-book=0.12.1
  - matplotlib>=3.1.1
  - dill>=0.3
  - pip
  - pip:
      - ghp-import
      - gym==0.21